FROM python:3.7

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "ruten_crawler.py" , "0001", "1", "6nnr87ac", "host.docker.internal"]